name: ng_bootstrap
version: 2.0.0
description: Angular 2 and Bootstrap 4
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Adao Jr. <itsjunnior@gmail.com>
  - Ismael Blasco <isdswii@gmail.com>
homepage: https://github.com/dart-league/ng_bootstrap
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  angular: ^7.0.2
  js_shims: ^1.0.0
  intl: ^0.17.0
  bootstrap_sass: ^4.3.1
  stream_transform: ^2.0.0
  font_awesome: ^5.10.1
  angular_forms: ^4.0.1
dev_dependencies:
  build_runner: any
  sass_builder: ^2.1.1