name: ng_bootstrap
version: 2.0.0
description: Angular 2 and Bootstrap 4
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Adao Jr. <itsjunnior@gmail.com>
  - Ismael Blasco <isdswii@gmail.com>
homepage: https://github.com/dart-league/ng_bootstrap
environment:
  sdk: '>=3.0.0 <4.0.0'
publish_to: none
dependencies:
  ngdart: ^8.0.0-dev.4
  node_shims: 
    git:
      url: https://github.com/icemanbsi/node_shims.git
      ref: master
  intl: ^0.18.1
  bootstrap_sass:
    git:
      url: https://github.com/icemanbsi/bootstrap_sass.git
      ref: master
  stream_transform: ^2.1.0
  font_awesome: 
    git:
     url: https://github.com/icemanbsi/Font-Awesome.git
     ref: master
  ngforms: ^5.0.0-dev.3
  string_converters: 
    git:
     url: https://github.com/icemanbsi/string_converters.git
     ref: master
dev_dependencies:
  build_runner: any
  sass_builder: ^2.1.1