name: ng_bootstrap_demo
version: 0.0.1
description: ng_bootstrap demo gh-page
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Adao Jr. <itsjunnior@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  string_converters: ^1.0.0
  angular: ^7.0.2
  # dson:
#  ng_bootstrap: ^0.6.3
  ng_bootstrap:
    path: ..
#    git: https://github.com/dart-league/ng_bootstrap
dev_dependencies:
  sass_builder: ^2.1.1
#  sass_builder:
#    path: ../sass_builder
  build_runner: ^2.1.5
  build_web_compilers: ^3.2.1
