name: ng_bootstrap_demo
version: 0.0.1
description: ng_bootstrap demo gh-page
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Adao Jr. <itsjunnior@gmail.com>

environment:
  sdk: '>=3.0.0 <4.0.0'
publish_to: none
dependencies:
  # dson: ^0.18.0
  string_converters: 
    git:
     url: https://github.com/icemanbsi/string_converters.git
     ref: master
#  ng_bootstrap: ^0.6.3
  ng_bootstrap:
    path: ..
    
dev_dependencies:
  build_runner: any
  sass_builder: ^2.1.1
